name: release
on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: [build] 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
    
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: publish
        env:
          crates_token: ${{ secrets.crates_token }}
        run: cargo publish --locked --token ${crates_token} --verbose