name: release
on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: [build, deny-check] 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout sources
      uses: actions/checkout@v2

    - name: publish
      env:
        crates_token: ${{ secrets.crates_token }}
      run: cargo publish --locked --token ${crates_token}  --verbose